// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { installationInstallationId, type InstallationInstallationId } from './Installation';
import { siteSiteId, type SiteSiteId } from './Site';
import { z } from 'zod';

/** Identifier type for public.note */
export type NoteNoteId = string & { __brand: 'NoteNoteId' };

/** Represents the table public.note */
export default interface Note {
  note_id: NoteNoteId;

  installation_id: InstallationInstallationId;

  site_id: SiteSiteId;

  title: string | null;

  body: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.note */
export interface NoteInitializer {
  /** Default value: gen_random_uuid() */
  note_id?: NoteNoteId;

  installation_id: InstallationInstallationId;

  site_id: SiteSiteId;

  title?: string | null;

  body?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.note */
export interface NoteMutator {
  note_id?: NoteNoteId;

  installation_id?: InstallationInstallationId;

  site_id?: SiteSiteId;

  title?: string | null;

  body?: string | null;

  created_at?: Date;

  updated_at?: Date;
}

export const noteNoteId = z.string() as unknown as z.Schema<NoteNoteId>;

export const note = z.object({
  note_id: noteNoteId,
  installation_id: installationInstallationId,
  site_id: siteSiteId,
  title: z.string().nullable(),
  body: z.string().nullable(),
  created_at: z.date(),
  updated_at: z.date(),
}) as unknown as z.Schema<Note>;

export const noteInitializer = z.object({
  note_id: noteNoteId.optional(),
  installation_id: installationInstallationId,
  site_id: siteSiteId,
  title: z.string().optional().nullable(),
  body: z.string().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
}) as unknown as z.Schema<NoteInitializer>;

export const noteMutator = z.object({
  note_id: noteNoteId.optional(),
  installation_id: installationInstallationId.optional(),
  site_id: siteSiteId.optional(),
  title: z.string().optional().nullable(),
  body: z.string().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
}) as unknown as z.Schema<NoteMutator>;
